[package]
name = "image-match-params"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
csv = "1.3.0"
hex = "0.4.3"
image = "0.24.6"
image-match = { path = "../image-match-rs", features = ["img"] }
imageproc = "0.24.0"
